FROM {{ user }}/debian:0.1

LABEL postgresql.version="9.4.9"

RUN apt update && \
    apt install -y postgresql postgresql-contrib && \
    rm -rf /var/{lib,log,cache}/apt && \
    pg_dropcluster 9.4 main

