FROM {{ user }}/debian:16.09.22

RUN apt update && \
    apt install -y redis-server && \
    rm -rf /var/{lib,log,cache}/apt

COPY redis.conf /etc/redis/redis.conf

CMD [ "redis-server", "/etc/redis/redis.conf" ]

