FROM {{ user }}/debian:0.1

LABEL redis.version="2.8.17"

RUN apt update && \
    apt install -y redis-server && \
    rm -rf /var/{lib,log,cache}/apt

COPY redis.conf /etc/redis/redis.conf

CMD [ "redis-server", "/etc/redis/redis.conf" ]

